#**Biblioteca numpy**

Funções básicas da Numpy

# 1. Definindo um array

In [ ]:
import numpy

# 1D array - 1 linha com 6 colunas
a = numpy.array([1, 2, 3, 4, 5, 6])
print(a.ndim)
print(a.shape)
print(a.size)

print("  ")

import numpy as np

# 1D array - 1 linha com 6 colunas
a = np.array([1, 2, 3, 4, 5, 6])
print(a.ndim)
print(a.shape)
print(a.size)

print("  ")

# 2D array - 3 linhas e 4 colunas
b = np.array([ [1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12] ])
print(b.ndim)
print(b.shape)
print(b.size)

n = 10
# array de zeros
zeros = np.zeros(n)

# array de 1
ones = np.ones((n,n))

# array vazio
empty = np.empty(n)

# array ordenado. Similar a função range()
order1 = np.arange(0,n,2) # 0 até n, de 2 em 2
order2 = np.linspace(0,1,n) # n números de 0 até 1
print(zeros)
print(ones)
print(empty)
print(order1)
print(order2)

# array complexo
c = np.array([[1, 2], [3, 4]], dtype=complex)
print(c)

1
(6,)
6
  
1
(6,)
6
  
2
(3, 4)
12
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0 2 4 6 8]
[0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]
[[1.+0.j 2.+0.j]
 [3.+0.j 4.+0.j]]


# 2. Reshape: mudando a forma

In [ ]:
arr = np.arange(6)

# remodelando: 3 linhas e 2 colunas
x = arr.reshape(3,2)
print(x)
print(x.flatten())
print(x.ravel())
print(x.T)




[[0 1]
 [2 3]
 [4 5]]
[0 1 2 3 4 5]
[0 1 2 3 4 5]
[[0 2 4]
 [1 3 5]]


# 3. Cópia de um array

Ao usar o operador de desígnio de variáveis '=' para criar um novo array, este ficará vinculado ao original e mudanças nele irão propagar entre os arrays

In [ ]:
y = np.array([1.5,65.8,30,54.5,100.1])
newarr1 = y
print(newarr1 is y)

newarr2 = y.copy()
print(newarr2 is y)


True
False


# 4. Indexando e fatiando um array

Similar ao aprendido para strings e listas

In [ ]:
a = np.arange(10)
print(a[0])
print(a[1:3])
print(a[::3])

# loop: Só utilizar quando necessário!
for i in a:
  print(a[i])

0
[1 2]
[0 3 6 9]
0
1
2
3
4
5
6
7
8
9


# 5. Operações

In [ ]:
a = np.arange(10,20,1)
b = np.arange(0,10,1)

# operações básicas: +,-,*,/,**
c = a + b
print(c)

# Funções matemáticas
c = np.exp(-b)
print(c)

[10 12 14 16 18 20 22 24 26 28]
[1.00000000e+00 3.67879441e-01 1.35335283e-01 4.97870684e-02
 1.83156389e-02 6.73794700e-03 2.47875218e-03 9.11881966e-04
 3.35462628e-04 1.23409804e-04]


# Dica importante!

In [ ]:
# preenchendo um array
arr = np.zeros(10)
for idx, val in enumerate(arr):
  arr[idx] = idx**2
print(arr)

# exemplo mais simples de broadcasting
arr = np.arange(10)**2
print(arr)

[ 0.  1.  4.  9. 16. 25. 36. 49. 64. 81.]
[ 0  1  4  9 16 25 36 49 64 81]


# (Extra) Números pseudo-aleatórios
Útil em métodos numéricos e ao analisarmos probabilidades e suas distribuições

In [ ]:
# entre 0 e 1
rnd = np.random.rand(10)
print(rnd)

# gaussiana de média mu e desvio padrão sigma
mu = 0
sigma = 1
rnd = np.random.normal(mu,sigma,10)
print(rnd)

# embaralhar
a = np.arange(10)
np.random.shuffle(a)
print(a)

# amostragem
a = np.random.uniform(0,100,100)
smp = np.random.choice(a,10)
print(smp)


[0.62815694 0.58226063 0.10015956 0.1981678  0.28963431 0.06497216
 0.02712036 0.08165593 0.64842721 0.84180335]
[ 0.25582138 -1.26807682  1.34591473  2.39577461  1.1284577  -0.20372282
 -0.25340953  1.30655757 -0.00666844 -0.76057742]
[0 3 4 6 5 2 8 1 9 7]
[45.36063298  7.67267501 56.35103761 57.24433516 79.95331611 76.18719814
 97.46488638 61.01553861 48.02370243 55.81768904]
